Loevgaard\SyliusBrandPlugin\Model\Brand:
    exclusion_policy: ALL
    xml_root_name: brand
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        name:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
    relations:
        -   rel: self
            href:
                route: loevgaard_sylius_brand_admin_api_brand_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
        -   rel: images
            href:
                route: loevgaard_sylius_brand_admin_api_brand_image_index
                parameters:
                    code: expr(object.getCode())
                    version: 1
            exclusion:
                groups: [Default]
        -   rel: products
            href:
                route: loevgaard_sylius_brand_admin_api_brand_product_index
                parameters:
                    code: expr(object.getCode())
                    version: 1
            exclusion:
                groups: [Default, Detailed]
